name = "Project Hatchet - Vanilla Land Vehicles"
prefix = "hatchet_vanilla"
author = "Project Hatchet"
mainprefix = "z"

include = ["./include"]
folder_optionals = true

releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]
