name = "Hatchet Vanilla Vehicles"
prefix = "hatchet_vanilla"
author = "Project Hatchet"
mainprefix = "z"

[files]
include = [
  "mod.cpp",
  "README.md",
  "LICENSE"
]

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "htc_vanilla"

[hemtt.launch.default]
workshop = [
  "450814997", # CBA_A3's Workshop ID
  "2941986336", # Hatchet Interaction Framework - Stable Version
]
